apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  containers:
    - name: nginx
      image: nginx

---

#Annotations $ Labels
apiVersion: v1
kind: Pod
metadata:
  name: pod02
  annotations:
    training/class: devops
  labels:
    type: test
spec:
  containers:
    - name: nginx
      image: nginx
---
#Resources
apiVersion: v1
kind: Pod
metadata:
  name: pod03
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---